Repository akamhy/waybackpy, pull requests merged in 2022-02, with the labels that each got.

#128 Typing
  .github/workflows/build-test.yml
  .github/workflows/unit-test.yml
  pytest.ini
  requirements-dev.txt
  requirements.txt
  setup.cfg
  tests/test_availability_api.py
  tests/test_cdx_api.py
  tests/test_cdx_snapshot.py
  tests/test_cdx_utils.py
  tests/test_save_api.py
  tests/test_utils.py
  waybackpy/__init__.py
  waybackpy/availability_api.py
  waybackpy/cdx_api.py
  waybackpy/cdx_snapshot.py
  waybackpy/cdx_utils.py
  waybackpy/cli.py
  waybackpy/exceptions.py
  waybackpy/save_api.py
  waybackpy/utils.py
  waybackpy/wrapper.py
Labels: enhancement

#141 added docstrings, added some static type hints and also lint.
  tests/test_cdx_utils.py
  waybackpy/availability_api.py
  waybackpy/cdx_api.py
  waybackpy/cdx_snapshot.py
  waybackpy/cdx_utils.py
  waybackpy/cli.py
  waybackpy/save_api.py
  waybackpy/utils.py
  waybackpy/wrapper.py
Labels: documentation

#149 Add tests
  .github/workflows/unit-test.yml
  tests/test_cli.py
  waybackpy/cdx_api.py
  waybackpy/cli.py
Labels: test

#156 add sort param support in CDX API class
  tests/test_cdx_utils.py
  waybackpy/cdx_api.py
  waybackpy/cdx_utils.py
Labels: enhancement

#159 Cdx based oldest newest and near
  tests/test_cdx_api.py
  tests/test_cdx_snapshot.py
  tests/test_cli.py
  waybackpy/availability_api.py
  waybackpy/cdx_api.py
  waybackpy/cdx_snapshot.py
  waybackpy/cli.py
  waybackpy/exceptions.py
  waybackpy/utils.py
Labels: enhancement
